import type { Metadata } from "next";

import "./globals.css";
import React from "react";
import {paragraphFont, subtitle} from "@/components/ui/fonts";
import NavBar from "@/components/layout/navBar/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={` ${paragraphFont.variable} ${subtitle.variable}`}  id={"home"}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
