import type { Metadata } from "next";

import "./globals.css";
import React from "react";
import {paragraphFont, titleFont} from "@/components/ui/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${titleFont.variable} ${paragraphFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
